[#insns-brev8,reftext="Reverse bits in bytes"]
=== brev8

Synopsis::
Reverse the bits in each byte of a source register.

Mnemonic::
brev8 _rd_, _rs_

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x13, attr: ['OP-IMM'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x5 },
    { bits:  5, name: 'rs' },
    { bits: 12, name: 0x687 }
]}
....

Description:: 
This instruction reverses the order of the bits in every byte of a register.

NOTE: This instruction is a specific encoding of a more generic instruction
which was originally proposed as part of the RISC-V Bitmanip extension
(`grevi`). Eventually, the more generic instruction may be standardised.
Until then, only the most common instances of it, such as this, are
being included in specifications.

Operation::
[source,sail]
--
result : xlenbits = EXTZ(0b0);
foreach (i from 0 to sizeof(xlen) by 8) {
    result[i+7..i] = reverse_bits_in_byte(X(rs1)[i+7..i]);
};
X(rd) = result;
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

|Zbkb (<<#zbkb>>)
|v1.0.0-rc3
|Frozen
|===

