[#insns-unzip,reftext="Unzip"]
=== unzip

Synopsis::
Place odd and even bits of the source word into upper/lower halves of the
destination.

Mnemonic::
unzip _rd_, _rs_

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 2, name: 0x3},
{bits: 5, name: 0x4},
{bits: 5, name: 'rd'},
{bits: 3, name: 0x5},
{bits: 5, name: 'rs1'},
{bits: 5, name: 0x0f},
{bits: 7, name: 0x4},
]}
....

Description:: 
This instruction places the even bits of the source register into the
low half of the destination, and the odd bits of the source into the
high bits of the destination.
It is the inverse of the <<insns-zip,zip>> instruction.
This instruction is available only on RV32.

NOTE: This instruction is a specific encoding of a more generic instruction
which was originally proposed as part of the RISC-V Bitmanip extension
(`unshfli`). Eventually, the more generic instruction may be standardised.
Until then, only the most common instances of it, such as this, are
being included in specifications.

Operation::
[source,sail]
--
foreach (i from 0 to xlen/2-1) {
  X(rd)[i       ] = X(rs1)[2*i  ]
  X(rd)[i+xlen/2] = X(rs1)[2*i+1]
}
--

.Software Hint
[NOTE, caption="SH" ]
===============================================================
This instruction is useful for implementing the SHA3 cryptographic
hash function on a 32-bit architecture, as it implements the
bit-interleaving operation used to speed up the 64-bit rotations
directly.
===============================================================

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

|Zbkb (<<#zbkb>>) (RV32)
|v1.0.0-rc3
|Frozen
|===


