[#insns-zip,reftext="Zip"]
=== zip

Synopsis::
Place upper/lower halves of the source register into odd/even bits of
the destination respectivley.

Mnemonic::
zip _rd_, _rs_

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 2, name: 0x3},
{bits: 5, name: 0x4},
{bits: 5, name: 'rd'},
{bits: 3, name: 0x1},
{bits: 5, name: 'rs1'},
{bits: 5, name: 0x0f},
{bits: 7, name: 0x4},
]}
....

Description:: 
This instruction places bits in the low half of the source register
into the even bit positions of the destination, and bits in the
high half of the source register into the odd bit positions of the
destination.
It is the inverse of the <<insns-unzip,unzip>> instruction.
This instruction is available only on RV32.

NOTE: This instruction is a specific encoding of a more generic instruction
which was originally proposed as part of the RISC-V Bitmanip extension
(`shfli`). Eventually, the more generic instruction may be standardised.
Until then, only the most common instances of it, such as this, are
being included in specifications.

Operation::
[source,sail]
--
foreach (i from 0 to xlen/2-1) {
  X(rd)[2*i  ] = X(rs1)[i       ]
  X(rd)[2*i+1] = X(rs1)[i+xlen/2]
}
--

.Software Hint
[NOTE, caption="SH" ]
===============================================================
This instruction is useful for implementing the SHA3 cryptographic
hash function on a 32-bit architecture, as it implements the
bit-interleaving operation used to speed up the 64-bit rotations
directly.
===============================================================

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

|Zbkb (<<#zbkb>>) (RV32)
|v1.0.0-rc3
|Frozen
|===

